AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'

Metrics/MethodLength:
  Exclude:
    - 'db/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/models/*'
    - 'spec/factories.rb'
    - 'lib/tasks/auto_annotate_models.rake'

Layout/SpaceAroundOperators:
  Enabled: false
