AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'

Metrics/MethodLength:
  Exclude:
    - 'db/**/*'
    - 'app/controllers/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/integration/**/*'
    - 'spec/models/*'
    - 'spec/services/**/*'
    - 'spec/factories/**/*'
    - 'spec/*_helper.rb'
    - 'lib/tasks/auto_annotate_models.rake'
    - 'config/environments/*'

Metrics/AbcSize:
  Exclude:
    - 'app/controllers/**/*'

Layout/SpaceAroundOperators:
  Enabled: false
