---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/contests/{id}/register":
    post:
      summary: Register user in contest
      tags:
      - Contest
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '201':
          description: |-
            contest application created. contest application stocks created.
                    assign contest application stocks
          content:
            application/json:
              example:
                error: an error occurred Finnhub couldn't find symbol AAPL
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                items:
                  type: array
                  items:
                    properties:
                      stock_id:
                        type: integer
                      multiplier:
                        type: integer
                    required:
                    - multiplier
                    - stock_id
                    - contest_application_id
consumes:
- application/json
produces:
- application/json
servers:
- url: "{defaultHost}"
  variables:
    defaultHost:
      default: http://localhost:3000
components:
  securitySchemes:
    accessToken:
      type: apiKey
      in: header
      name: Access-Token
    client:
      type: apiKey
      in: header
      name: Client
    uid:
      type: apiKey
      in: header
      name: UID
security:
- accessToken: []
  client: []
  uid: []
