---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/auth/":
    post:
      summary: Creates a user
      tags:
      - Auth
      parameters: []
      responses:
        '200':
          description: user created
          content:
            application/json:
              example:
                status: success
                data:
                  email: ulysses_renner@fritsch.net
                  email_validated: false
                  id: 3322
                  fantasy_points: 0
                  coins: 0
                  uid: ulysses_renner@fritsch.net
                  username: larue_schumm#1
                  preferred_lang: ru_RU
                  avatar_id:
                  created_at: '2021-12-22T14:37:51.390Z'
                  updated_at: '2021-12-22T14:37:51.400Z'
                  provider: email
                  allow_password_change: false
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
              - username
              - email
              - password
consumes:
- application/json
produces:
- application/json
servers:
- url: "{defaultHost}"
  variables:
    defaultHost:
      default: http://localhost:3000
