defaults: &defaults
  origins:
    - <%= ENV['APP_DOMAIN'] || "unicorn.a6raywa1cher.com" %>
    - www.<%= ENV['APP_DOMAIN'] || "unicorn.a6raywa1cher.com" %>


development:
  <<: *defaults
  origins:
    - <%= ENV['APP_DOMAIN'] || "unicorn.a6raywa1cher.com" %>
    - www.<%= ENV['APP_DOMAIN'] || "unicorn.a6raywa1cher.com" %>
    - localhost:9000

test:
  <<: *defaults

production:
  <<: *defaults
