defaults: &defaults
  div1:
    fantasy_points_threshold: 300
    contests_amount: 3
    coins_entry_fee_range: 5..20
    reg_duration_range: 2..15
    summarizing_duration_range: 5..20

  div2:
    fantasy_points_threshold: 600
    contests_amount: 2
    coins_entry_fee_range: 21..50
    reg_duration_range: 2..15
    summarizing_duration_range: 5..20

  div3:
    fantasy_points_threshold: 900
    contests_amount: 1
    coins_entry_fee_range: 51..100
    reg_duration_range: 2..15
    summarizing_duration_range: 5..20

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults