defaults: &defaults
  div1:
    fantasy_points_threshold: 300
    contests_amount: 4
    coins_entry_fee_range: 20..30
    reg_duration_range: 2..5
    summarizing_duration_range: 2..5
    base_points: 100
    base_coins_delta: 50
    base_fp_delta: 50

  div2:
    fantasy_points_threshold: 800
    contests_amount: 2
    coins_entry_fee_range: 50..70
    reg_duration_range: 2..5
    summarizing_duration_range: 2..5
    base_points: 100
    base_coins_delta: 120
    base_fp_delta: 75

  div3:
    fantasy_points_threshold: 1200
    contests_amount: 2
    coins_entry_fee_range: 100..200
    reg_duration_range: 2..5
    summarizing_duration_range: 2..5
    base_points: 100
    base_coins_delta: 300
    base_fp_delta: 100

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults